### ISSUE TITLE
Exported images have some dash-lines on the bottom

### ISSUE THREAD

**Issue by cuixiping** [dnomd343/HRD_Game#2]
![image](https://user-images.githubusercontent.com/1104492/221087554-554e4ad5-1fc5-42e4-a1e7-c7a9ddf7c7f5.png)

Exported images have some dash-lines on the bottom.
Is this a bug or has a special purpose?

**Comment by dnomd343** [comment]
This is not a dashed line, but a small part of the truncated string, which should be `E7E3C68`, aka the text encoding for this layout.

As for why it appears, combined with #1, it should be that your system is a streamlined version, which lacks some components necessary for OCX rendering, and the exported image is BMP format witch directly rendered based on the control in VB6. The imperfect display leads to the deviation in the size of the image (may be caused by the border), so there are a few extra pixels on the right and bottom of the exported picture. In the code, there is a built-in option for encoding text below the image, and the encoding will still be rendered when it is turned off. However, it will be truncated when exported, and a part of it appears because the bottom becomes larger, which looks the same as a dashed line.

My suggestion is to install the runtime required by VB6, or use the full version of the system (ISO from Microsoft), and you can also consider opening the option to add text code.

**Comment by cuixiping** [comment]
Thank you for the detailed explanation.
I tested on both Win7 Ultimate and Win10 Enterprise Edition, both full version, and the bug is still exist. 
The issue is not critical.
It looks as expected if  the option of add text code is on.
